services:
  ai-app:
    image: ai-project1-ai-app:latest
    build:
      context: .\ai-app
      dockerfile: .\ai-app/Dockerfile
    init: true
    volumes:
      - type: bind 
        source: .\ai-app
        target: /usr/src/app
    networks:
      - backend
    ports:
      - 7860:7860
  ai-models:
    image: ai-project1-ai-models:latest
    build:
      context: .\ai-models\
      dockerfile: .\ai-models\Dockerfile
    init: true
    volumes:
      - type: bind 
        source: .\ai-models\
        target: /usr/src/app
    networks:
      - backend
    ports:
      - 8080:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  backend:
